# Generated by Django 5.1.1 on 2024-11-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_payment_remove_shipping_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='status',
            field=models.CharField(default='In progress', max_length=20),
        ),
    ]
