# Generated by Django 5.1.1 on 2024-12-08 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_order_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shopping.payment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shopping.shipping'),
            preserve_default=False,
        ),
    ]
