# Generated by Django 5.1.1 on 2024-09-20 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('CLIENTE', 'Cliente'), ('VENDITORE', 'Venditore')], default='CLIENTE', max_length=20)),
                ('nome', models.CharField(blank=True, max_length=50)),
                ('cognome', models.CharField(blank=True, max_length=50)),
                ('partita_iva', models.CharField(blank=True, max_length=20)),
                ('email_aziendale', models.EmailField(blank=True, max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
