# Generated by Django 5.1.1 on 2024-11-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered_user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='email',
        ),
    ]
