# Generated by Django 5.1.1 on 2024-11-17 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='reg_user',
        ),
    ]
