# Generated by Django 5.1.1 on 2024-10-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_product_alter_review_user_seller_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='created_at',
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='seller_review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
