# Generated by Django 5.1.1 on 2024-10-29 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SP', 'Spam'), ('SC', 'Scam'), ('IP', 'Inappropriate'), ('OT', 'Other')], max_length=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.registered_user')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.seller')),
            ],
        ),
    ]
