# Generated by Django 5.1.1 on 2024-11-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_strike'),
    ]

    operations = [
        migrations.AddField(
            model_name='strike',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
