# Generated by Django 5.1.1 on 2024-11-22 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_remove_strike_seen_report_seen'),
        ('users', '0002_remove_registered_user_email_remove_seller_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.registered_user'),
        ),
    ]
