# Generated by Django 5.1.1 on 2024-11-22 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_report_unique_together_alter_report_reporter'),
        ('users', '0002_remove_registered_user_email_remove_seller_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.registered_user'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('reporter', 'seller')},
        ),
    ]
