# Generated by Django 5.1.1 on 2024-10-21 08:00

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to=listings.models.product_image_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=listings.models.product_image_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=listings.models.product_image_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=listings.models.product_image_path)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=listings.models.product_image_path)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('sold', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(related_name='products', to='listings.category')),
            ],
        ),
    ]
