# Generated by Django 5.1.1 on 2024-09-27 17:37

import django.db.models.deletion
import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to=listings.models.product_image_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=listings.models.product_image_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=listings.models.product_image_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=listings.models.product_image_path)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=listings.models.product_image_path)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.seller')),
            ],
        ),
    ]
