# Generated by Django 5.1.1 on 2024-09-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_category_product_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
