# Generated by Django 5.1.1 on 2024-10-17 07:56

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_product_image1_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(upload_to=listings.models.product_image_path),
        ),
    ]
