# Generated by Django 5.1.1 on 2024-10-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
